# Generated by Django 5.2.3 on 2025-07-01 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CriminalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('defendant_name', models.CharField(max_length=255)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('sex', models.CharField(blank=True, max_length=20, null=True)),
                ('race', models.CharField(blank=True, max_length=50, null=True)),
                ('case_number', models.CharField(max_length=100, unique=True)),
                ('date_filed', models.DateField(blank=True, null=True)),
                ('charges', models.TextField(blank=True, null=True)),
                ('arrest_citation_date', models.DateField(blank=True, null=True)),
                ('parish', models.CharField(blank=True, max_length=100, null=True)),
                ('alert_available', models.BooleanField(default=False)),
                ('scraped_timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
